### ISSUE TITLE
UI ONLY DISPLAY HALF?

### ISSUE THREAD

**Issue by Myoko** [TheRealCain532/PS4-Debugger#1]
i got an issues! the ui not fully displayed  OS Windows 10 1803
https://prnt.sc/l0cdw3

**Comment by TheRealCain532** [comment]
That's very strange! Could possibly be a resolution issue, what is your display resolution? Could also be the native text size for Windows if you edited those at all. Let me know and I will do my best to fix it!!

**Comment by Myoko** [comment]
2K 2560X1440 display resolution  and 150% DPI

**Comment by TheRealCain532** [comment]
I unfortunately do not have a 2K monitor, however I did try to change my text size and other such things to 150% but that did not yield the same error that you are getting. Can you do me a favor and check the latest build and let me know if you are still having the same issues?

**Comment by Myoko** [comment]
i got it! i will tried the latest build, and thank you

**Comment by Myoko** [comment]
it's the same issues in 1.0.0.6
https://prnt.sc/l126gs

**Comment by TheRealCain532** [comment]
Try to change the compatibility settings of the .exe and play around with the "Change DPI" settings. I still haven't been able to find a work around apart from making the window sizeable (which could potentially cause other errors :X) Please keep me posted!!
